baseURL = "https://erinskidds.com/blog"
languageCode = "en-us"
title = "Erin's blog"
theme = "terminal"
paginate = 5

[params]
  # Terminal theme specific settings
  contentTypeName = "posts"
  themeColor = "teal"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[permalinks]
  posts = "/posts/:slug/"

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[languages]
  [languages.en]
    title = "Erin's blog"
    subtitle = "Where a Software Engineer posts ideas."
    keywords = "blog, software engineer, full stack, front end, back end"
    copyright = "© 2025 Erin Skidds"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Erin's Blog"
      logoHomeLink = "/blog"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Portfolio"
        url = "https://erinskidds.com"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"